#! /usr/bin/env bash
#
#   Copyright (c) 2018 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"


MULLE_EXECUTABLE_VERSION=0.0.2
MULLE_EXECUTABLE_BASHFUNCTIONS="1"


#
# This is the main user interface to mulle-monitor
# sorta like git
#

trap_fail()
{
   exit 1
}


SHOWN_COMMANDS="\
   init           : create a new project
   run            : monitor files and run scripts"

HIDDEN_COMMANDS="\
   callback       : execute a callback
   find           : find files that match
   libexec-dir    : print path to mulle-monitor libexec
   match          : match filenames
   task           : execute a task
   uname          : mulle-monitors simplified uname(1)"


print_commands()
{
   local show_all="${1:-NO}"

   echo "${SHOWN_COMMANDS}"

   if [ "${show_all}" != "NO" ]
   then
      echo "${HIDDEN_COMMANDS}"
   fi
}


print_flags()
{
   local delimiter

   delimiter="          : "

   echo "   -e   ${delimiter}bypass mulle-env check"
   echo "   -f   ${delimiter}force operation"

   options_technical_flags_usage "${delimiter}"
}


_usage()
{
   local verbose="${1:-NO}"
   local error="${2}"

   if [ ! -z "${error}" ]
   then
      log_error "${error}"
   fi

   cat <<EOF
Usage:
   ${MULLE_EXECUTABLE_NAME} [flags] [command] [options]

   The filesystem monitor. Call functions based on directory and
   file changed. There are numerous possiblities to filter which
   function is called. Functions are loaded via plugins.

Flags:
EOF
   print_flags  | sort


   cat <<EOF

Commands:
EOF

   print_commands "${verbose}" | sort

   if [ "${verbose}" = "NO" ]
   then
      cat <<EOF
      (use mulle-monitor -v help to show more commands)
EOF
   fi

   cat <<EOF

   Options are command specific. Use ${MULLE_EXECUTABLE_NAME} <command> -h for help.
EOF

   exit 1
}


usage()
{
   _usage "$@" >&2
   exit 1
}

#
# stolen from:
# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
# ----
#
_prepend_path_if_relative()
{
   case "$2" in
      /*)
         echo "$2"
      ;;
      *)
         echo "$1/$2"
      ;;
   esac
}


resolve_symlinks()
{
   local dir_context
   local linkpath

   if linkpath="`readlink "$1"`"
   then
      dir_context=`dirname -- "$1"`
      resolve_symlinks "`_prepend_path_if_relative "${dir_context}" "${linkpath}"`"
   else
      echo "$1"
   fi
}


monitor_libexec_path()
{
   local executablepath="$1"

   local exedir
   local exedirpath
   local prefix
   local libexecpath

   case "${executablepath}" in
      \.*|/*|~*)
      ;;

      *)
         executablepath="`command -v "${executablepath}"`"
      ;;
   esac

   executablepath="`resolve_symlinks "${executablepath}"`"
   exedirpath="`dirname "${executablepath}"`"
   prefix="`dirname "${exedirpath}"`"
   libexecpath="${prefix}/libexec/mulle-monitor"

   if [ ! -x "${libexecpath}/mulle-monitor-run.sh" ]
   then
      libexecpath="${exedirpath}/src"
   fi

   case "$libexecpath" in
      /*|~*)
      ;;

      *)
         libexecpath="$PWD/$libexecpath"
      ;;
   esac

   if [ -x "${libexecpath}/mulle-monitor-run.sh" ]
   then
      echo "${libexecpath}"
   fi
}


_init()
{
   #
   # minimal setup exit
   #
   if [ "$1" = "version" ]
   then
      echo "${MULLE_EXECUTABLE_VERSION}"
      exit 0
   fi

   MULLE_MONITOR_LIBEXEC_DIR="`monitor_libexec_path "$0"`"
   if [ -z "${MULLE_MONITOR_LIBEXEC_DIR}" ]
   then
      echo "$0 fatal error: Could not find libexec ($PWD)" >&2
      exit 1
   fi

   #
   # minimal setup exit
   #
   case "$1" in
      "libexec-dir"|"library-path")
         echo "${MULLE_MONITOR_LIBEXEC_DIR}"
         exit 0
      ;;
   esac

   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
   [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
      echo "mulle-bashfunctions-env not installed" >&2 && \
      exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   #  set -e # more pain then gain in the end
   #  set -u # doesn't work with my style

   trap trap_fail INT
   set -o pipefail
}


monitor_environment()
{
   log_entry "monitor_environment" "$@"

   # lame but practical
   if [ -z "${MULLE_MONITOR_DIR}" ]
   then
      if [ -d ".mulle-sde" ]
      then
         log_fluff "MULLE_MONITOR_DIR default is .mulle-sde"
         MULLE_MONITOR_DIR=".mulle-sde"
      else
         log_fluff "MULLE_MONITOR_DIR default is .mulle-monitor"
         MULLE_MONITOR_DIR=".mulle-monitor"
      fi
   fi

   MULLE_MONITOR_ETC_DIR="${MULLE_MONITOR_ETC_DIR:-${MULLE_MONITOR_DIR}/etc}"

   case "${MULLE_MONITOR_MATCH_DIR}" in
      NO)
         MULLE_MONITOR_MATCH_DIR=""
         log_fluff "Not using \"MULLE_MONITOR_MATCH_DIR\""
      ;;

      "")
         MULLE_MONITOR_MATCH_DIR="${MULLE_MONITOR_ETC_DIR}/match.d"
         if [ ! -d "${MULLE_MONITOR_MATCH_DIR}" ]
         then
            MULLE_MONITOR_MATCH_DIR="${MULLE_MONITOR_DIR}/share/match.d"
         fi
         if [ ! -d "${MULLE_MONITOR_MATCH_DIR}" ]
         then
            log_warning "There is no directory \"${MULLE_MONITOR_MATCH_DIR}\" set up"
            MULLE_MONITOR_MATCH_DIR=""
         fi
      ;;
   esac

   case "${MULLE_MONITOR_IGNORE_DIR}" in
      NO)
         MULLE_MONITOR_IGNORE_DIR=""
         log_fluff "Not using \"MULLE_MONITOR_IGNORE_DIR\""
      ;;

      "")
         MULLE_MONITOR_IGNORE_DIR="${MULLE_MONITOR_ETC_DIR}/ignore.d"
         if [ ! -d "${MULLE_MONITOR_IGNORE_DIR}" ]
         then
            MULLE_MONITOR_IGNORE_DIR="${MULLE_MONITOR_DIR}/share/ignore.d"
         fi
         if [ ! -d "${MULLE_MONITOR_IGNORE_DIR}" ]
         then
            log_fluff "There is no directory \"${MULLE_MONITOR_IGNORE_DIR}\" set up"
            MULLE_MONITOR_IGNORE_DIR=""
         fi
      ;;
   esac
}


main()
{
   local MULLE_FLAG_MAGNUM_FORCE="NO"

   # technical flags
   local MULLE_FLAG_EXEKUTOR_DRY_RUN="NO"
   local MULLE_FLAG_LOG_LOCAL="NO"
   local MULLE_FLAG_LOG_DEBUG="NO"
   local MULLE_FLAG_LOG_EXEKUTOR="NO"
   local MULLE_FLAG_LOG_FLUFF="NO"
   local MULLE_FLAG_LOG_SCRIPTS="NO"
   local MULLE_FLAG_LOG_SETTINGS="NO"
   local MULLE_FLAG_LOG_VERBOSE="NO"
   local MULLE_FLAG_LOG_MERGE="NO"
   local MULLE_TRACE_POSTPONE="NO"

   #
   # simple option handling
   #
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -e)
            FLAG_OUTSIDE_ENV="YES"
         ;;

         -cd|--config-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "missing argument to \"$1\""
            shift

            MULLE_MONITOR_DIR="$1"
         ;;

         -ed|--etc-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "missing argument to \"$1\""
            shift

            MULLE_MONITOR_ETC_DIR="$1"
         ;;

         -md|--match-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "missing argument to \"$1\""
            shift

            MULLE_MONITOR_MATCH_DIR="$1"
         ;;

         -id|--ignore-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "missing argument to \"$1\""

            MULLE_MONITOR_IGNORE_DIR="$1"
         ;;

         -h|--help)
            usage "${MULLE_TRACE}"
         ;;

         --version)
            echo "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         -*)
            log_error "Unknown option \"$1\""
            usage "${MULLE_TRACE}"
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}"

   local cmd

   cmd="$1"
   [ $# -ne 0 ] && shift

   MULLE_EXECUTABLE_FAIL_PREFIX="`concat "${MULLE_EXECUTABLE_NAME}" "${cmd}" `"

   if [ "${FLAG_OUTSIDE_ENV}" = "YES" ]
   then
      MULLE_VIRTUAL_ROOT="${PWD}"
      export MULLE_VIRTUAL_ROOT
   fi

   if [ -z "${MULLE_VIRTUAL_ROOT}" ]
   then
      case "${cmd}" in
         run|match|find)
            fail "To run ${MULLE_EXECUTABLE_NAME} outside of mulle-env, pass the -e flag"
         ;;
      esac
   fi

   MULLE_EXECUTABLE_OPTIONS="$@"

   monitor_environment

   case "${cmd}" in
      help)
         usage "${MULLE_TRACE}"
      ;;

      callback)
         # shellcheck source=src/mulle-monitor-callback.sh
         . "${MULLE_MONITOR_LIBEXEC_DIR}/mulle-monitor-callback.sh"

         monitor_callback_main "$@"
      ;;

      libexec-dir|library-path)
         echo "${MULLE_MONITOR_LIBEXEC_DIR}"
      ;;

      match)
         # shellcheck source=src/mulle-monitor-match.sh
         . "${MULLE_MONITOR_LIBEXEC_DIR}/mulle-monitor-match.sh"

         monitor_match_main "$@"
      ;;

      find)
         # shellcheck source=src/mulle-monitor-run.sh
         . "${MULLE_MONITOR_LIBEXEC_DIR}/mulle-monitor-find.sh"

         monitor_find_main "$@"
      ;;

      # for the user it's a sde, but internally we call it
      # a clone for historical reasons, and also monitor_monitor is
      # stupid
      run)
         # shellcheck source=src/mulle-monitor-run.sh
         . "${MULLE_MONITOR_LIBEXEC_DIR}/mulle-monitor-run.sh"

         monitor_run_main "$@"
      ;;

      task)
         # shellcheck source=src/mulle-monitor-task.sh
         . "${MULLE_MONITOR_LIBEXEC_DIR}/mulle-monitor-task.sh"

         monitor_task_main "$@"
      ;;

      uname)
         echo "${UNAME}"
      ;;

      version)
         echo "${MULLE_EXECUTABLE_VERSION}"
         return 0
      ;;

      *)
         MULLE_EXECUTABLE_FAIL_PREFIX="${MULLE_EXECUTABLE_NAME}"
         log_error "Unknown command \"${cmd}\""
         usage "${MULLE_TRACE}"
      ;;
   esac
}


_init "$@" # needs params
main "$@"
