#! /usr/bin/env bash
#
#   Copyright (c) 2018 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"


MULLE_EXECUTABLE_VERSION=0.0.9
MULLE_EXECUTABLE_BASHFUNCTIONS="1"


#
# This is the main user interface to mulle-match
#

trap_fail()
{
   exit 1
}


print_commands()
{
   local show_all="${1:-NO}"

   SHOWN_COMMANDS="\
   clean          : remove cached patternfiles
   find           : find files that match patternfiles
   match          : match filenames against patternfiles
   patternfile    : manage patternfiles"

   HIDDEN_COMMANDS="\
   libexec-dir    : print path to mulle-match libexec
   uname          : mulle-matchs simplified uname(1)"


   echo "${SHOWN_COMMANDS}"

   if [ "${show_all}" != "NO" ]
   then
      echo "${HIDDEN_COMMANDS}"
   fi
}


print_hidden_flags()
{
   echo "   -cd <dir>      : set MULLE_MATCH_DIR"
   echo "   -ed <dir>      : set MULLE_MATCH_ETC_DIR"
   echo "   -id <dir>      : set MULLE_MATCH_IGNORE_DIR"
   echo "   -md <dir>      : set MULLE_MATCH_MATCH_DIR"
}


print_flags()
{
   local show_all="${1:-NO}"

   local delimiter

   delimiter="          : "

   if [ "${show_all}" != "NO" ]
   then
      print_hidden_flags
   fi

   echo "   -e   ${delimiter}bypass mulle-env check"
   echo "   -f   ${delimiter}force operation"

   options_technical_flags_usage "${delimiter}"
}


_usage()
{
   local verbose="${1:-NO}"
   local error="${2}"

   if [ ! -z "${error}" ]
   then
      log_error "${error}"
   fi

   cat <<EOF
Usage:
   ${MULLE_USAGE_NAME} [flags] [command]

   Match filenames to a user-definable set of patternfiles.
   Also: find alls files matching those patternfiles.

Flags:
EOF
   print_flags "${verbose}" | sort


   cat <<EOF

Commands:
EOF

   print_commands "${verbose}" | sort

   if [ "${verbose}" = "NO" ]
   then
      cat <<EOF
      (use mulle-match -v help to show more commands)
EOF
   fi

   cat <<EOF

   Use ${MULLE_USAGE_NAME} <command> -h for topical help.
EOF

   exit 1
}


usage()
{
   _usage "$@" >&2
   exit 1
}


main()
{
   local MULLE_FLAG_MAGNUM_FORCE="NO"

   # technical flags
   local MULLE_FLAG_EXEKUTOR_DRY_RUN="NO"
   local MULLE_FLAG_LOG_LOCAL="NO"
   local MULLE_FLAG_LOG_DEBUG="NO"
   local MULLE_FLAG_LOG_EXEKUTOR="NO"
   local MULLE_FLAG_LOG_FLUFF="NO"
   local MULLE_FLAG_LOG_SCRIPTS="NO"
   local MULLE_FLAG_LOG_SETTINGS="NO"
   local MULLE_FLAG_LOG_VERBOSE="NO"
   local MULLE_FLAG_LOG_MERGE="NO"
   local MULLE_TRACE_POSTPONE="NO"

   #
   # simple option handling
   #
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h*|--help|help)
            usage "${MULLE_TRACE}"
         ;;

         -cd|--config-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "missing argument to \"$1\""
            shift

            MULLE_MATCH_DIR="$1"
         ;;

         -e)
            FLAG_OUTSIDE_ENV="YES"
         ;;

         -ed|--etc-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "missing argument to \"$1\""
            shift

            MULLE_MATCH_ETC_DIR="$1"
         ;;

         -f)
            MULLE_FLAG_MAGNUM_FORCE="YES"
         ;;

         -id|--ignore-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "missing argument to \"$1\""

            MULLE_MATCH_IGNORE_DIR="$1"
         ;;

         -md|--match-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "missing argument to \"$1\""
            shift

            MULLE_MATCH_MATCH_DIR="$1"
         ;;

         --version)
            echo "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         -*)
            log_error "Unknown option \"$1\""
            usage "${MULLE_TRACE}"
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}"

   local cmd

   cmd="$1"
   [ $# -ne 0 ] && shift

   if [ "${FLAG_OUTSIDE_ENV}" = "YES" ]
   then
      MULLE_VIRTUAL_ROOT="${PWD}"
      export MULLE_VIRTUAL_ROOT
   fi

   if [ -z "${MULLE_VIRTUAL_ROOT}" ]
   then
      case "${cmd}" in
         find|match)
            fail "To run ${MULLE_EXECUTABLE_NAME} outside of mulle-env, \
pass the -e flag"
         ;;
      esac
   fi

   local physdir

   physdir="`pwd -P`"

   [ -d "${physdir}" ]      || fail "Working directory \"${PWD}\" does not exist"
   exekutor cd "${physdir}" || fail "Could not cd to physical directory \"${physdir}\""

   MULLE_EXECUTABLE_OPTIONS="$@"

   . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-environment.sh" || exit 1

   match_environment

   case "${cmd}" in
      help)
         usage "${MULLE_TRACE}"
      ;;

      clean)
         # shellcheck source=src/mulle-match-clean.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-clean.sh"

         match_clean_main "$@"
      ;;

      libexec-dir|library-path)
         echo "${MULLE_MATCH_LIBEXEC_DIR}"
      ;;

      match)
         # shellcheck source=src/mulle-match-match.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-match.sh"

         match_match_main "$@"
      ;;

      find)
         # shellcheck source=src/mulle-match-run.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-find.sh"

         match_find_main "$@"
      ;;

      patternfile)
         # shellcheck source=src/mulle-match-patternfile.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-patternfile.sh"

         match_patternfile_main "$@"
      ;;

      uname)
         echo "${UNAME}"
      ;;

      version)
         echo "${MULLE_EXECUTABLE_VERSION}"
         return 0
      ;;

      "")
         usage "${MULLE_TRACE}"
      ;;

      *)
         log_error "Unknown command \"${cmd}\""
         usage "${MULLE_TRACE}"
      ;;
   esac
}


########
###
### INIT
###
_init()
{
   #
   # minimal setup exit
   #
   if [ "$1" = "version" ]
   then
      echo "${MULLE_EXECUTABLE_VERSION}"
      exit 0
   fi

   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
   then
      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
      if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
      then
         if [ -z "`command -v "${executablepath}"`" ]
         then
             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
         else
            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
         fi
         exit 1
      fi
   fi

      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || \
      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"

   local _libexec_dir

   _get_libexec_dir "$0" "mulle-match" "mulle-match-match.sh"

   MULLE_MATCH_LIBEXEC_DIR="${_libexec_dir}"

   #
   # minimal setup exit
   #
   case "$1" in
      "libexec-dir"|"library-path")
         echo "${MULLE_MATCH_LIBEXEC_DIR}"
         exit 0
      ;;
   esac

   #  set -e # more pain then gain in the end
   #  set -u # doesn't work with my style

   trap trap_fail INT
   set -o pipefail

   MULLE_ARGUMENTS="$*"
}
###
### INIT
###
########


_init "$@" # needs params
main "$@"
