#! /usr/bin/env mulle-bash
# shellcheck shell=bash
#
#   Copyright (c) 2018 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE:-}" = 'YES' -o "${MULLE_MATCH_TRACE:-}" = 'YES' ] && set -x && : "$0" "$@"



MULLE_EXECUTABLE_VERSION=1.0.3
MULLE_EXECUTABLE_BASHFUNCTIONS="1"

#
# Determine location of own libexec directory. Which is `src` in development
# and ../libexec when deployed. MULLE_EXECUTABLE needs to be defined for this.
#

if [ -z "${MULLE_MATCH_LIBEXEC_DIR}" ]
then
   r_get_libexec_dir "${MULLE_EXECUTABLE}" "mulle-match" "mulle-match-init.sh"
   MULLE_MATCH_LIBEXEC_DIR="${RVAL}"
fi


#
# This is the match::main user interface to mulle-match
#
match::print_commands()
{
   local show_all="${1:-NO}"

   SHOWN_COMMANDS="\
   init        : setup some initial patternfiles
   clean       : remove cached patternfiles
   list        : list files that match patternfiles (default)
   filename    : find the patternfile that matches a filename
   patternfile : manage patternfiles"

   HIDDEN_COMMANDS="\
   libexec-dir : print path to mulle-match libexec
   uname       : mulle-match's simplified uname(1)"


   printf "%s\n" "${SHOWN_COMMANDS}"

   if [ "${show_all}" != 'NO' ]
   then
      printf "%s\n" "${HIDDEN_COMMANDS}"
   fi
}


match::print_flags()
{
   local show_all="${1:-NO}"

   local delimiter

   delimiter="       : "

   echo "   -f   ${delimiter}force operation"
   echo "   -P   ${delimiter}specify search start points (separator :)"
   echo "   -I   ${delimiter}specify files and folders to ignore (separator :)"
   echo "   -F   ${delimiter}specify file pattern to match (separator :)"

   options_technical_flags_usage "${delimiter}"
}


match::do_usage()
{
   local verbose="${1:-NO}"
   local error="${2}"

   if [ ! -z "${error}" ]
   then
      log_error "${error}"
   fi

   cat <<EOF
Usage:
   ${MULLE_USAGE_NAME} [flags] [command]

   Manage patternfiles, that are used to type and categorize files, with
   the "patternfile" command.

   Lists all file matching those patternfiles with the "list" command. For
   example:
      mulle-match list -tf header    # list all headers in mulle-objc projects

   You can use the "filename" command, to test, which patternfile matches a 
   given filename. This command can also check, if a specific patternfile 
   matches a filename. This can be useful, when the output of "list" 
   doesn't match your expectations.

Flags:
EOF
   match::print_flags "${verbose}" | LC_ALL=C sort


   cat <<EOF

Commands:
EOF

   match::print_commands "${verbose}" | LC_ALL=C sort

   if [ "${verbose}" = 'NO' ]
   then
      cat <<EOF
      (use mulle-match -v help to show more commands)
EOF
   fi

   cat <<EOF

   Use ${MULLE_USAGE_NAME} <command> -h for topical help.
EOF
}


match::usage()
{
   match::do_usage "$@" >&2
   exit 1
}


match::main()
{
   #
   # simple option handling
   #
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h*|--help|help)
            match::usage "${MULLE_TRACE}"
         ;;

         -f)
            MULLE_FLAG_MAGNUM_FORCE='YES'
         ;;

         -F|--filename-patterns)
            [ $# -eq 1 ] && match::usage "missing argument to $1"
            shift

            MULLE_MATCH_FILENAMES="$1"
         ;;

         -I|--ignore-path)
            [ $# -eq 1 ] && match::usage "missing argument to $1"
            shift

            MULLE_MATCH_IGNORE_PATH="$1"
         ;;

         -P|--path)
            [ $# -eq 1 ] && match::usage "missing argument to $1"
            shift

            MULLE_MATCH_PATH="$1"
         ;;

         --version)
            printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         -*)
            log_error "Unknown option \"$1\""
            match::usage "${MULLE_TRACE}"
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}" && set -x

   local cmd

   if [ $# -ne 0 ]
   then
      cmd="$1"
      shift
   fi

   if [ -z "${MULLE_VIRTUAL_ROOT}" ]
   then
      MULLE_VIRTUAL_ROOT="`pwd -P`"
      [ "${MULLE_VIRTUAL_ROOT}" = "/" ] && fail "Can't run with root folder as starting place"
      log_fluff "mulle-fetch sets MULLE_VIRTUAL_ROOT to \"${MULLE_VIRTUAL_ROOT}\""
   else
      rexekutor cd "${MULLE_VIRTUAL_ROOT}" || fail "Could not cd to \"${MULLE_VIRTUAL_ROOT}\""
   fi

   . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-environment.sh" || exit 1

   match::environment::init "" "${cmd}"

   case "${cmd:-list}" in
      help)
         match::usage "${MULLE_TRACE}"
      ;;

      clean)
         # shellcheck source=src/mulle-match-clean.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-clean.sh"

         match::clean::main "$@"
      ;;

      init)
         # shellcheck source=src/mulle-match-list.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-init.sh"

         match::init::main "$@"
      ;;

      libexec-dir|library-path)
         printf "%s\n" "${MULLE_MATCH_LIBEXEC_DIR}"
      ;;

      list|find)
         # shellcheck source=src/mulle-match-list.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-list.sh"

         match::list::main "$@"
      ;;

      filename|match)
         # shellcheck source=src/mulle-match-filename.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-filename.sh"

         match::filename::main "$@"
      ;;

      patternfile|patternfiles)
         # shellcheck source=src/mulle-match-patternfile.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-patternfile.sh"

         match::patternfile::main "$@"
      ;;

      # commands like 'padd' are "expanded" into "patternfile add"
      p*)
         # shellcheck source=src/mulle-match-patternfile.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-patternfile.sh"

         match::patternfile::main "${1:1}" "$@"
      ;;

      categories)
         # shellcheck source=src/mulle-match-patternfile.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-patternfile.sh"

         MULLE_FLAG_LOG_TERSE='YES'
         match::patternfile::list match.d --no-output-file-marker | sed -n -e 's/[0-9]*-.*--\(.*\)$/\1/p'
      ;;

      types)
         # shellcheck source=src/mulle-match-patternfile.sh
         . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-patternfile.sh"

         MULLE_FLAG_LOG_TERSE='YES'
         match::patternfile::list match.d --no-output-file-marker | sed -n -e 's/[0-9]*-\(.*\)--.*$/\1/p'
      ;;

      uname)
         printf "%s\n" "${MULLE_UNAME}"
      ;;


      version)
         printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
         return 0
      ;;

      "")
         match::usage "${MULLE_TRACE}"
      ;;

      *)
         log_error "Unknown command \"${cmd}\""
         match::usage "${MULLE_TRACE}"
      ;;
   esac
}

call_with_flags "match::main" "${MULLE_MATCH_FLAGS}" "$@"

