#! /usr/bin/env bash

[ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"


expect_match_filepath()
{
   log_entry "expect_match_print_filepath" "$@"

   local expected="$1"; shift
   local ignore_patterncaches="$1"
   local match_patterncaches="$2"
   local filepath="$3"

   local result

   if ! result="`match_filepath "$@"`"
   then
      fail "Pattern \"${pattern}\" did not match filepath \"${filepath}\""
   fi

   if [ "${result}" != "${expected}" ]
   then
      fail "Result \"${result}\" was expected to be \"${expected}\""
   fi
}


expect_match_print_filepath()
{
   log_entry "expect_match_print_filepath" "$@"

   local expected="$1"; shift
   local format="$1"
   local ignore_patterncaches="$2"
   local match_patterncaches="$3"
   local filepath="$4"

   local result

   if ! result="`match_print_filepath "$@"`"
   then
      fail "Pattern \"${pattern}\" did not match filepath \"${filepath}\""
   fi

   if [ "${result}" != "${expected}" ]
   then
      fail "Result \"${result}\" was expected to be \"${expected}\""
   fi
}


main()
{
   MULLE_MONITOR_FLAGS="$@"

   _options_mini_main "$@"

   #
   # memo: remember we only deal with relative paths w/o leading /!
   # for simplicity it's also assumed that no relative path contain a
   # trailing '/'
   #
   local ignore
   local match

   local _cache

   _cache=
   _patterncaches_passing_filter "ignore" ""
   ignore="${_cache}"

   _cache=
   _patterncaches_passing_filter "match" ""
   match="${_cache}"

   expect_match_filepath "1-a--"  "${ignore}" "${match}" "a"
   expect_match_filepath "2-b--x" "${ignore}" "${match}" "b"
   expect_match_filepath "4-aa--" "${ignore}" "${match}" "aa"
   expect_match_filepath "4-aa--" "${ignore}" "${match}" "aaa"

   log_verbose "----- #1 PASSED -----"

   expect_match_print_filepath "a;1-a--;a"     "%t;%m;%f\\n"    "${ignore}" "${match}" "a"
   expect_match_print_filepath "b;x;2-b--x;b"  "%t;%c;%m;%f\\n" "${ignore}" "${match}" "b"
   expect_match_print_filepath "b;X;2-b--x;b"  "%t;%I;%m;%f\\n" "${ignore}" "${match}" "b"
   expect_match_print_filepath "aa;4-aa--;aa"  "%t;%m;%f\\n"    "${ignore}" "${match}" "aa"
   expect_match_print_filepath "aa;4-aa--;aaa" "%t;%m;%f\\n"    "${ignore}" "${match}" "aaa"

   log_verbose "----- #2 PASSED -----"

   log_info "----- ALL PASSED -----"
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_MONITOR="${MULLE_MONITOR:-${PWD}/../../mulle-monitor}"

   MULLE_MONITOR_LIBEXEC_DIR="`"${MULLE_MONITOR}" "libexec-dir"`" || exit 1

   . "${MULLE_MONITOR_LIBEXEC_DIR}/mulle-monitor-match.sh" || exit 1
}


init "$@"
main "$@"

