#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


expect_matching_filepath_pattern()
{
   log_entry "expect_match_print_filepath" "$@"

   local expected="$1"; shift
   local ignore_patterncaches="$1"
   local match_patterncaches="$2"
   local filepath="$3"

   local result

   if ! result="`match::filename::matching_filepath_pattern "$@"`"
   then
      fail "Pattern \"${pattern}\" did not match filepath \"${filepath}\""
   fi

   if [ "${result}" != "${expected}" ]
   then
      fail "Result \"${result}\" was expected to be \"${expected}\""
   fi
}


expect_match_print_filepath()
{
   log_entry "expect_match_print_filepath" "$@"

   local expected="$1"; shift
   local format="$1" ; shift
   local ignore_patterncaches="$1"
   local match_patterncaches="$2"
   local filename="$3"

   local result

   shell_disable_glob
   IFS=$'\n'

   if ! result="`match::filename::match_print_filepath "${format}" "" "$@"`"
   then
      fail "Pattern \"${pattern}\" did not match filename \"${filename}\""
   fi

   if [ "${result}" != "${expected}" ]
   then
      fail "Result \"${result}\" was expected to be \"${filename}\""
   fi

   IFS="${DEFAULT_IFS}"
}


main()
{
   MULLE_MATCH_FLAGS="$@"

   _options_mini_main "$@" && set -x

   shell_enable_extglob
   #
   # memo: remember we only deal with relative paths w/o leading /!
   # for simplicity it's also assumed that no relative path contain a
   # trailing '/'
   #
   local ignore
   local match

   match::filename::r_define_patternfilefunctions "ignore" ""
   ignore="${RVAL}"

   match::filename::r_define_patternfilefunctions "match" ""
   match="${RVAL}"

   expect_matching_filepath_pattern "1-a--"  "${ignore}" "${match}" "a"
   expect_matching_filepath_pattern "2-b--x" "${ignore}" "${match}" "b"
   expect_matching_filepath_pattern "4-aa--" "${ignore}" "${match}" "aa"
   expect_matching_filepath_pattern "4-aa--" "${ignore}" "${match}" "aaa"

   log_verbose "----- #1 PASSED -----"

   expect_match_print_filepath "a;1-a--;a"     "%t;%m;%f\\n"    "${ignore}" "${match}" "a"
   expect_match_print_filepath "b;x;2-b--x;b"  "%t;%c;%m;%f\\n" "${ignore}" "${match}" "b"
   expect_match_print_filepath "b;X;2-b--x;b"  "%t;%C;%m;%f\\n" "${ignore}" "${match}" "b"
   expect_match_print_filepath "aa;4-aa--;aa"  "%t;%m;%f\\n"    "${ignore}" "${match}" "aa"
   expect_match_print_filepath "aa;4-aa--;aaa" "%t;%m;%f\\n"    "${ignore}" "${match}" "aaa"

   log_verbose "----- #2 PASSED -----"

   log_info "----- ALL PASSED -----"
}


init()
{
   MULLE_MATCH="${MULLE_MATCH:-${PWD}/../../mulle-match}"

   MULLE_MATCH_LIBEXEC_DIR="`"${MULLE_MATCH}" "libexec-dir"`" || exit 1

   . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-filename.sh" || exit 1
}


init "$@"
main "$@"

