#! /usr/bin/env bash

[ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"


expect_find_filenames()
{
   log_entry "expect_find_filenames" "$@"

   local expected="$1"; shift

   local result

   result="`find_filenames "$@" | sort`"

   if [ "${result}" != "${expected}" ]
   then
      fail "Result \"${result}\" was expected to be \"${expected}\""
   fi
}


main()
{
   MULLE_MATCH_FLAGS="$@"

   _options_mini_main "$@"

   #
   # memo: remember we only deal with relative paths w/o leading /!
   # for simplicity it's also assumed that no relative path contain a
   # trailing '/'
   #
   shopt -s extglob

   local expected
   local ignore
   local match
   local _cache

   _patternfilefunctions_passing_filter "ignore.d" ""
   ignore="${_cache}"

   _patternfilefunctions_passing_filter "match.d" "source"
   match="${_cache}"

   #-----------
   expected="src/foo.c
src/main.c"

   expect_find_filenames "${expected}" "%f\\n" "${ignore}" "${match}"
   log_verbose "----- #1 PASSED -----"

   #-----------
   _patternfilefunctions_passing_filter "match.d" "header"
   match="${_cache}"

   expected="src/foo.h"
   expect_find_filenames "${expected}" "%f\\n" "${ignore}" "${match}"

   log_verbose "----- #2 PASSED -----"

   #-----------
   _patternfilefunctions_passing_filter "match.d" "header"
   match="${_cache}"

   expected="foo/wrong.h
src/foo.h"
   expect_find_filenames "${expected}" "%f\\n" "" "${match}"

   log_verbose "----- #3 PASSED -----"

   #-----------

   log_info "----- ALL PASSED -----"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_MATCH="${MULLE_MATCH:-${PWD}/../../mulle-match}"

   MULLE_MATCH_LIBEXEC_DIR="`"${MULLE_MATCH}" "libexec-dir"`" || exit 1

   . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-match.sh" || exit 1
   . "${MULLE_MATCH_LIBEXEC_DIR}/mulle-match-find.sh" || exit 1
}


init "$@"
main "$@"

