#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_match()
{
   echo "####################################" >&2
   echo mulle-match ${MULLE_MATCH_FLAGS} "$@"  >&2
   echo "####################################" >&2

   "${MULLE_MATCH}" ${MULLE_MATCH_FLAGS} "$@" || fail "\`mulle-match $*\` failed"
}


expect_mulle_match()
{
   log_entry "expect_mulle_match" "$@"

   local expected="$1"; shift

   local result

   result="`run_mulle_match "$@"`" || exit 1

   if [ "${result}" != "${expected}" ]
   then
      fail "Result \"${result}\" was expected to be \"${expected}\""
   fi
}


expect_failure_mulle_match()
{
   log_entry "expect_failure_mulle_match" "$@"

   local result

   if result="`run_mulle_match "$@"`"
   then
      fail "Did not fail unexpectedly"
   else
      log_info "Failed as expected"
   fi
}


main()
{
   MULLE_MATCH_FLAGS="$@"

   _options_mini_main "$@" && set -x

   #-----------

   expect_mulle_match "01-type0negative--all" match "a"
   expect_mulle_match "02-type0positive--all" match "b"
   expect_failure_mulle_match match "c"

   log_verbose "----- #1 PASSED -----"

   log_info "----- ALL PASSED -----"
}



init()
{
   MULLE_MATCH="${MULLE_MATCH:-${PWD}/../../mulle-match}"
}


init "$@"
main "$@"

