#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_match()
{
   echo "####################################" >&2
   echo mulle-match ${MULLE_MATCH_FLAGS} "$@"  >&2
   echo "####################################" >&2

   "${MULLE_MATCH}" ${MULLE_MATCH_FLAGS} "$@" || fail "\`mulle-match $*\` failed"
}


expect_mulle_match()
{
   log_entry "expect_mulle_match" "$@"

   local expected="$1"; shift

   local result

   result="`run_mulle_match "$@"`" || exit 1

   if [ "${result}" != "${expected}" ]
   then
      fail "Result \"${result}\" was expected to be \"${expected}\""
   fi
}


expect_failure_mulle_match()
{
   log_entry "expect_failure_mulle_match" "$@"

   local result

   if result="`run_mulle_match "$@"`"
   then
      fail "Did not fail unexpectedly"
   fi
}


main()
{
   MULLE_MATCH_FLAGS="$@"

   _options_mini_main "$@" && set -x

   #-----------

   expect_mulle_match "00-vfl--none" patternfile -i list --output-no-file-marker
   expect_mulle_match "00-bochum--all" patternfile -m list --output-no-file-marker

   log_verbose "----- #1 PASSED -----"

   #-----------

   expect_mulle_match "vfl" patternfile -i cat "00-vfl--none"
   expect_mulle_match "bochum" patternfile cat "00-bochum--all"

   log_verbose "----- #2 PASSED -----"

   run_mulle_match patternfile copy "00-bochum--all" "02-bochum--some"
   run_mulle_match patternfile rename "02-bochum--some" "02-bochum--more"
   expect_mulle_match "bochum" patternfile cat "00-bochum--all"
   if ! run_mulle_match patternfile remove "02-bochum--more"
   then
      fail "failed to remove"
   fi

   log_verbose "----- #4 PASSED -----"

   log_info "----- ALL PASSED -----"
}



init()
{
   MULLE_MATCH="${MULLE_MATCH:-${PWD}/../../mulle-match}"
}


init "$@"
main "$@"

